version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./postgres.env

  web:
    build:
      context: .
      dockerfile: dockerfile.prod
    command: bash -c "python manage.py collectstatic --no-input --clear && gunicorn django_test.wsgi:application --bind 0.0.0.0:8000"
    container_name: projects
    env_file:
      - ./django.env
      - ./postgres.env
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/code/staticfiles
      - ./certs:/etc/nginx/certs

volumes:
  postgres-data:
  static_volume: