# Generated by Django 3.0.3 on 2020-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20200206_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
