# Generated by Django 3.0.3 on 2020-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_auto_20200206_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='end_time',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
