# Generated by Django 3.0.3 on 2020-02-06 11:10

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_auto_20200206_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
    ]
